version = 1

[[annotations]]
path = ["**/*.md", "**/*.json", "**/*.png", "**/*.jpg", "**/*.svg", ".gitignore"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Observes io LTD"
SPDX-License-Identifier = "LicenseRef-PolyForm-Internal-Use-1.0.0"

